#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > sudo tee /var/www/html/index.html
echo "HEllo World!" > sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
