#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
# Configure HAproxy
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 18.210.14.153:80 check\n\tserver server2 34.229.69.147:80 check\n" >> /etc/haproxy/haproxy.cfg'
# Restart HAproxy
sudo service haproxy restart
