#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive out of it.

if [ -z "$1" ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

# mysql dump file name
dump_file="backup.sql"

# compressed archive name format: day-month-year.tar.gz
archive_name="$(date +'%d-%m-%Y').tar.gz"

#MySQL root password
root_password="$1"

# Perform mysql dump
mysqldump -u root -p"${root_password}" --all-databases > "${dump_file}"

# Check if the mysqldump command was successful
if [ $? -ne 0 ]; then
    echo "MySQL dump failed. Check your credentials and try again."
    exit 1
fi

# create a compressed archive
tar -czf "${archive_name}" "${dump_file}"

rm "${dump_file}"
echo "${dump_name}"
