#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
file="/etc/passwd"
while IFS=":" read -r NAME PASS USER_ID GROUP_ID INFO HOME SHELL _
do
  echo "The user $NAME is part of the $GROUP_ID gang, lives in $HOME and rides $SHELL. $USER_ID's place is protected by the passcode $PASS, more info about the user here: $INFO"
done < $file
