#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes.
min=1
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $min -le 59 ]
	do
		echo $min
		((min++))
	done
	((h++))
	min=1
done
