#!/usr/bin/env bash
#Script that installs ufw firewall and setup a few rules on a server

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw enable
sudo ufw status
sudo default deny incoming
sudo default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw status                 
