#!/usr/bin/env bash
#Script that install ufw firewall and setup a few rules on a server

sudo apt-get update
sudo apt-get -y install ufw
sudo ufw status
sudo default deny incoming
sudo default allow outgoing
sudo ufw allow "22/tcp"
sudo ufw allow "443/tcp"
sudo ufw allow "80/tcp"
echo "y" | sudo ufw enable
sudo ufw status
~                 
