#!/usr/bin/env bash
#Forwording ports

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw enable
sudo ufw status
sudo default deny incoming
sudo default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 8080/tcp
sudo ufw status
sudo apt-get install iptables-persistent
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo netfilter-persistent save
sudo netfilter-persistent reload
sudo iptables -t nat -L
