#!/usr/bin/env bash
#Script that configures Nginx to run as nginx and to be listning on 
#all active IPs on port 8080


sudo service nginx stop
echo "user nginx;" >> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
